### ISSUE TITLE
owncloud integration supports http but not https

### ISSUE THREAD

**Issue by legacychimera247** [Wedmer/cargodock#3]
well the title says it all...
tried with my jolla community italia cloud account and was working till we implemented https adress, from that on there was no way to make it work...

**Comment by Wedmer** [comment]
There's SSL option in OwnCloud settings. Does it work?

**Comment by Wedmer** [comment]
Just tested with https://demo12.nextcloud.bayton.org/
Everything works.
Test this settings, please:
```
Server: jollacommunity.it
Path: /cloud/remote.php/webdav
Secure connection: SSL

**Comment by legacychimera247** [comment]
i will test it when i'll come back home...thanks...

**Comment by legacychimera247** [comment]
tested and perfectly working...old one was not working...thanks...
