### ISSUE TITLE
Txt Viewer/Editor 

### ISSUE THREAD

**Issue by ghost** [Wedmer/cargodock#9]
Viewing a .txt file is very hard. I have to scroll right, right, right and back and so on. Could you tell your viewer to convert the text to fit the screen?

**Comment by ghost** [comment]
What about an "open with" option?

**Comment by Wedmer** [comment]
I'm working on "tools" list that can be used to open files.
As directly using of libcontentaction isn't allowed by Harbour rules, I can't check which files have registered types in the system.

**Comment by Wedmer** [comment]
[Tools added](https://github.com/pycage/cargodock/pull/19)
You can use external editor now. Tested with [tIDE](https://openrepos.net/content/eekkelund/tide)

**Comment by ghost** [comment]
Uhh. Hard stuff. How do I add the Jolla documents app for example? Does it also work with android apps?

**Comment by Wedmer** [comment]
It can work with applications you can start from console. For Sailfish Office command line in settings will be `sailfish-office %1`.
MIME based file handling will be added when I have free time.

**Comment by ghost** [comment]
Okay, that works. Thanks a lot. But now it's going to be complicated: I figured out how to open a Android App in the terminal. I own an Android Office app called TextMaker that can edit copy paste etc. doc, docx etc. I can start it with 
`apkd-launcher "/data/app/softmaker.applications.textmakertrial-1.apk" softmaker.applications.textmakertrial/softmaker.applications.textmakertrial.TextMaker`
That also works in Cargo Dock. But if I add the %1 nothing happens. Without %1 the app start without opening the choosed document. How/Where can I add the %1? The Usage of apkd-launcher is: 
`apkd-launcher <apkfile> <package>/<activity>`

**Comment by Wedmer** [comment]
It seems that this app can't open files in this way or access is denied.

**Comment by dasDirksche** [comment]
A pitty. Thanks for your patience.

Am Mittwoch, 28. März 2018 schrieb Vladimir Ulrich:

**Comment by ghost** [comment]
What a pitty. Thanks a lot for your patience.

**Comment by ghost** [comment]
And thanks for the Tool Feature. It's very helpfull

**Comment by Wedmer** [comment]
Anyway mime-based file opening will be added, so Android apps will be usable.

**Comment by ghost** [comment]
Wedmer, i just have see after the new update of sfos 2.2 it seems the tools options dont open a file anymore with %1 i try it with sailfish-office and harbour-editor but none opens anymore the file...

**Comment by Wedmer** [comment]
I can't test it before 2.2 release for Jolla 1.

**Comment by Wedmer** [comment]
Tools feature works for me on 2.2

**Comment by Wedmer** [comment]
No response for a long time. Some functionality was implemented.
